// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eMsg.proto

#include "eMsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
namespace common {
PROTOBUF_CONSTEXPR ExternalMessage::ExternalMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.validmsg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cmdcode_)*/0
  , /*decltype(_impl_.protocolswitch_)*/0
  , /*decltype(_impl_.cmdmerge_)*/0
  , /*decltype(_impl_.responsestatus_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ExternalMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExternalMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExternalMessageDefaultTypeInternal() {}
  union {
    ExternalMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExternalMessageDefaultTypeInternal _ExternalMessage_default_instance_;
}  // namespace common
}  // namespace pb
static ::_pb::Metadata file_level_metadata_eMsg_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_eMsg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_eMsg_2eproto = nullptr;

const uint32_t TableStruct_eMsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::common::ExternalMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::common::ExternalMessage, _impl_.cmdcode_),
  PROTOBUF_FIELD_OFFSET(::pb::common::ExternalMessage, _impl_.protocolswitch_),
  PROTOBUF_FIELD_OFFSET(::pb::common::ExternalMessage, _impl_.cmdmerge_),
  PROTOBUF_FIELD_OFFSET(::pb::common::ExternalMessage, _impl_.responsestatus_),
  PROTOBUF_FIELD_OFFSET(::pb::common::ExternalMessage, _impl_.validmsg_),
  PROTOBUF_FIELD_OFFSET(::pb::common::ExternalMessage, _impl_.data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::pb::common::ExternalMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::pb::common::_ExternalMessage_default_instance_._instance,
};

const char descriptor_table_protodef_eMsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\neMsg.proto\022\tpb.common\"\204\001\n\017ExternalMess"
  "age\022\017\n\007cmdCode\030\001 \001(\005\022\026\n\016protocolSwitch\030\002"
  " \001(\005\022\020\n\010cmdMerge\030\003 \001(\005\022\026\n\016responseStatus"
  "\030\004 \001(\005\022\020\n\010validMsg\030\005 \001(\t\022\014\n\004data\030\006 \001(\014b\006"
  "proto3"
  ;
static ::_pbi::once_flag descriptor_table_eMsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_eMsg_2eproto = {
    false, false, 166, descriptor_table_protodef_eMsg_2eproto,
    "eMsg.proto",
    &descriptor_table_eMsg_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_eMsg_2eproto::offsets,
    file_level_metadata_eMsg_2eproto, file_level_enum_descriptors_eMsg_2eproto,
    file_level_service_descriptors_eMsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_eMsg_2eproto_getter() {
  return &descriptor_table_eMsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_eMsg_2eproto(&descriptor_table_eMsg_2eproto);
namespace pb {
namespace common {

// ===================================================================

class ExternalMessage::_Internal {
 public:
};

ExternalMessage::ExternalMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.common.ExternalMessage)
}
ExternalMessage::ExternalMessage(const ExternalMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ExternalMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.validmsg_){}
    , decltype(_impl_.data_){}
    , decltype(_impl_.cmdcode_){}
    , decltype(_impl_.protocolswitch_){}
    , decltype(_impl_.cmdmerge_){}
    , decltype(_impl_.responsestatus_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.validmsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validmsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_validmsg().empty()) {
    _this->_impl_.validmsg_.Set(from._internal_validmsg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.cmdcode_, &from._impl_.cmdcode_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.responsestatus_) -
    reinterpret_cast<char*>(&_impl_.cmdcode_)) + sizeof(_impl_.responsestatus_));
  // @@protoc_insertion_point(copy_constructor:pb.common.ExternalMessage)
}

inline void ExternalMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.validmsg_){}
    , decltype(_impl_.data_){}
    , decltype(_impl_.cmdcode_){0}
    , decltype(_impl_.protocolswitch_){0}
    , decltype(_impl_.cmdmerge_){0}
    , decltype(_impl_.responsestatus_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.validmsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.validmsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ExternalMessage::~ExternalMessage() {
  // @@protoc_insertion_point(destructor:pb.common.ExternalMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ExternalMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.validmsg_.Destroy();
  _impl_.data_.Destroy();
}

void ExternalMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ExternalMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.common.ExternalMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.validmsg_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.cmdcode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.responsestatus_) -
      reinterpret_cast<char*>(&_impl_.cmdcode_)) + sizeof(_impl_.responsestatus_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExternalMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 cmdCode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.cmdcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 protocolSwitch = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.protocolswitch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 cmdMerge = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.cmdmerge_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 responseStatus = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.responsestatus_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string validMsg = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_validmsg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.common.ExternalMessage.validMsg"));
        } else
          goto handle_unusual;
        continue;
      // bytes data = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ExternalMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.common.ExternalMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cmdCode = 1;
  if (this->_internal_cmdcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_cmdcode(), target);
  }

  // int32 protocolSwitch = 2;
  if (this->_internal_protocolswitch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_protocolswitch(), target);
  }

  // int32 cmdMerge = 3;
  if (this->_internal_cmdmerge() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_cmdmerge(), target);
  }

  // int32 responseStatus = 4;
  if (this->_internal_responsestatus() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_responsestatus(), target);
  }

  // string validMsg = 5;
  if (!this->_internal_validmsg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_validmsg().data(), static_cast<int>(this->_internal_validmsg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.common.ExternalMessage.validMsg");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_validmsg(), target);
  }

  // bytes data = 6;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.common.ExternalMessage)
  return target;
}

size_t ExternalMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.common.ExternalMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string validMsg = 5;
  if (!this->_internal_validmsg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_validmsg());
  }

  // bytes data = 6;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // int32 cmdCode = 1;
  if (this->_internal_cmdcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cmdcode());
  }

  // int32 protocolSwitch = 2;
  if (this->_internal_protocolswitch() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_protocolswitch());
  }

  // int32 cmdMerge = 3;
  if (this->_internal_cmdmerge() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cmdmerge());
  }

  // int32 responseStatus = 4;
  if (this->_internal_responsestatus() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_responsestatus());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ExternalMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ExternalMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ExternalMessage::GetClassData() const { return &_class_data_; }


void ExternalMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ExternalMessage*>(&to_msg);
  auto& from = static_cast<const ExternalMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.common.ExternalMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_validmsg().empty()) {
    _this->_internal_set_validmsg(from._internal_validmsg());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_cmdcode() != 0) {
    _this->_internal_set_cmdcode(from._internal_cmdcode());
  }
  if (from._internal_protocolswitch() != 0) {
    _this->_internal_set_protocolswitch(from._internal_protocolswitch());
  }
  if (from._internal_cmdmerge() != 0) {
    _this->_internal_set_cmdmerge(from._internal_cmdmerge());
  }
  if (from._internal_responsestatus() != 0) {
    _this->_internal_set_responsestatus(from._internal_responsestatus());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ExternalMessage::CopyFrom(const ExternalMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.common.ExternalMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExternalMessage::IsInitialized() const {
  return true;
}

void ExternalMessage::InternalSwap(ExternalMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.validmsg_, lhs_arena,
      &other->_impl_.validmsg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExternalMessage, _impl_.responsestatus_)
      + sizeof(ExternalMessage::_impl_.responsestatus_)
      - PROTOBUF_FIELD_OFFSET(ExternalMessage, _impl_.cmdcode_)>(
          reinterpret_cast<char*>(&_impl_.cmdcode_),
          reinterpret_cast<char*>(&other->_impl_.cmdcode_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ExternalMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_eMsg_2eproto_getter, &descriptor_table_eMsg_2eproto_once,
      file_level_metadata_eMsg_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::common::ExternalMessage*
Arena::CreateMaybeMessage< ::pb::common::ExternalMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::common::ExternalMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
